---
- name: Demo playbook to test callback plugin - Deployment
  hosts: all
  tasks:
    
    - name: Install httpd package
      dnf:
        name: httpd
        state: latest
    
    - name: Start and enable httpd service
      service:
        name: httpd
        enabled: true
        state: started

    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
         <!DOCTYPE html>
         <html>
         <body>

         <h1 style="background-color:DodgerBlue;">Hello Welcome to ansible automation platform</h1>
         <p style="background-color:Tomato;">to learn more visit below website</p>
         <a href="https://www.ansible.com">ansible.com</a>  

         </body>
         </html> 
